### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by joelhellman** [Fuhrmann/keypirinha-faker-data#1]
I get an error when I have installed and loaded the FakeData plugin. I tried a manual install and an install with [Package Control](https://github.com/ueffel/Keypirinha-PackageControl), but had the same error. I have no trouble installing other plugins. 

I run a portable install of Keypirinha, version 2.19. 
Faker Data version 1.0.
OS: Windows 10 Pro - 10.0.16299 Build 16299

Keypirinha console output:

```
17:23:35.265 Python: Traceback (most recent call last):
17:23:35.265 Python:   File "keypirinha_private.py", line 356, in reload_module
17:23:35.265 Python:   File "lib\importlib\__init__.py", line 126, in import_module
17:23:35.265 Python:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
17:23:35.265 Python:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
17:23:35.265 Python:   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
17:23:35.265 Python:   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
17:23:35.265 Python:   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
17:23:35.265 Python:   File "keypirinha_private.py", line 246, in load_module
17:23:35.265 Python:   File "C:\portable\keypirinha\portable\Profile\InstalledPackages\FakerData.keypirinha-package\fakerdata.py", line 11, in <module>
17:23:35.265 Python:   File "C:\portable\keypirinha\portable\Profile\InstalledPackages\Fakerdata.keypirinha-package\lib\faker\__init__.py", line 4, in <module>
17:23:35.265 Python:     from faker.factory import Factory
17:23:35.265 Python:   File "C:\portable\keypirinha\portable\Profile\InstalledPackages\Fakerdata.keypirinha-package\lib\faker\factory.py", line 10, in <module>
17:23:35.265 Python:     from faker.config import DEFAULT_LOCALE, PROVIDERS, AVAILABLE_LOCALES
17:23:35.265 Python:   File "C:\portable\keypirinha\portable\Profile\InstalledPackages\Fakerdata.keypirinha-package\lib\faker\config.py", line 14, in <module>
17:23:35.265 Python:     AVAILABLE_LOCALES = find_available_locales(PROVIDERS)
17:23:35.265 Python:   File "C:\portable\keypirinha\portable\Profile\InstalledPackages\Fakerdata.keypirinha-package\lib\faker\utils\loading.py", line 32, in find_available_locales
17:23:35.265 Python:     provider_module = import_module(provider_path)
17:23:35.265 Python:   File "lib\importlib\__init__.py", line 126, in import_module
17:23:35.265 Python:   File "C:\portable\keypirinha\portable\Profile\InstalledPackages\Fakerdata.keypirinha-package\lib\faker\providers\address\__init__.py", line 6, in <module>
17:23:35.265 Python:     from .. import date_time
17:23:35.265 Python:   File "C:\portable\keypirinha\portable\Profile\InstalledPackages\Fakerdata.keypirinha-package\lib\faker\providers\date_time\__init__.py", line 11, in <module>
17:23:35.265 Python:     from dateutil import relativedelta
17:23:35.265 Python:   File "C:\portable\keypirinha\portable\Profile\InstalledPackages\Fakerdata.keypirinha-package\lib\dateutil\relativedelta.py", line 8, in <module>
17:23:35.265 Python:     from six import integer_types
17:23:35.265 Python: ModuleNotFoundError: No module named 'six'
```

**Comment by Fuhrmann** [comment]
That's really strange. 

Could  you try to update to the last Keypirinha version and try again (if it's not a problem)? I am too using the portable but I'm in v2.21 version. 

I'm using Windows 10 Pro but in the 1803 update.

**Comment by joelhellman** [comment]
I updated to v2.21 and it works now. Thanks.

**Comment by Fuhrmann** [comment]
Good to know!

**Comment by LeLocTai** [comment]
I'm having this issue in 2.22. I already has six installed on my computer

**Comment by Fuhrmann** [comment]
I was able to only reply now. Sorry about that. Is the problem still happening?

**Comment by LeLocTai** [comment]
ok I forgot about this. I solved this by copying six.py from my installation of Python to Keypirinha's

**Comment by Fuhrmann** [comment]
Ok, good to know, thanks for the feedback!

**Comment by DrorHarari** [comment]
Hi @Fuhrmann would you consider adding six.py to your package so we won't need to copy it to Keypirinha's folder to get rid of the error?

What's strange is that after installation, it seemed to work OK but then after some time I noticed the module not found error.

If @polyvertex is not including it, then it will be best for you to include it.

**Comment by loogaru** [comment]
Same on fresh install. Issue not closed

**Comment by Fuhrmann** [comment]
> Hi @Fuhrmann would you consider adding six.py to your package so we won't need to copy it to Keypirinha's folder to get rid of the error?
> 
> What's strange is that after installation, it seemed to work OK but then after some time I noticed the module not found error.
> 
> If @polyvertex is not including it, then it will be best for you to include it.

Yes, I can! Thanks for the feedback. I'm not using windows at this moment, but I can setup a virtual machine to solve this problem, I just need some time.

> Same on fresh install. Issue not closed

Thanks for the feedback!
